module.exports = {
  modelName: "Pro/zai-org/GLM-5",
  apiKey: process.env.LLM_API_KEY,
  apiBaseUrl: "https://api.siliconflow.cn/v1/chat/completions",
  codeReviewDir: "agents-workspace/code-review",
  patternsDir: "agents-workspace/patterns",
  metricsDir: "agents-workspace/metrics",
  rulesDir: ".cursor/rules",
  proposalsDir: ".cursor/rule-proposals",
  businessCodeFilePatterns: [/\.(?:ts|tsx|js|jsx|json)$/i],
  projectConfigFilePatterns: [
    /(^|\/)package\.json$/i,
    /(^|\/)pnpm-(?:lock|workspace)\.yaml$/i,
    /(^|\/)tsconfig(?:\..+)?\.json$/i,
    /(^|\/)\.cnb\.yml$/i,
    /(^|\/)(?:Dockerfile|docker-compose(?:\..+)?\.ya?ml)$/i,
    /(^|\/)\.env(?:\.[^/.]+)?(?:\.example)?$/i,
    /(^|\/)\.npmrc$/i,
    /(^|\/)(?:\.eslintrc(?:\..+)?|eslint\.config\.(?:js|cjs|mjs|ts))$/i,
    /(^|\/)(?:\.prettierrc(?:\..+)?|prettier\.config\.(?:js|cjs|mjs|ts))$/i,
  ],
  postCommitReviewMaxRuntimeMs: 20 * 60 * 1000,
};
